"""Render the repository's bilingual changelogs without third-party dependencies.

Run before deployment; --check detects stale generated output without writing.
The supported Markdown subset is intentionally small: headings, paragraphs,
unordered lists and inline links. Extend it explicitly when the source needs more.
"""
import argparse
import html
from pathlib import Path
import re

ROOT = Path(__file__).resolve().parent.parent
PUBLIC = ROOT / "website" / "public"
REPO = "https://github.com/adoin/git-Agent/blob/main/"


def inline(text):
    parts = []
    offset = 0
    for match in re.finditer(r"\[([^\]]+)\]\(([^)]+)\)", text):
        parts.append(html.escape(text[offset:match.start()]))
        label, target = match.groups()
        if target in ("CHANGELOG.md", "CHANGELOG.zh-CN.md"):
            target = "?lang=" + ("zh" if "zh-CN" in target else "en")
        elif target in ("LICENSE", "NOTICE"):
            target = REPO + target
        elif not target.startswith("https://"):
            raise ValueError(f"Unsupported changelog link: {target}")
        parts.append(f'<a href="{html.escape(target, quote=True)}">{html.escape(label)}</a>')
        offset = match.end()
    parts.append(html.escape(text[offset:]))
    return "".join(parts)


def render_markdown(source):
    output, paragraph = [], []
    in_list = False

    def flush():
        if paragraph:
            output.append("<p>" + inline(" ".join(paragraph)) + "</p>")
            paragraph.clear()

    for line in source.splitlines():
        if not line.startswith("- ") and in_list:
            output.append("</ul>")
            in_list = False
        if not line.strip():
            flush()
        elif line.startswith("#"):
            flush()
            heading = re.fullmatch(r"(#{1,3}) (.+)", line)
            if not heading:
                raise ValueError(f"Unsupported heading: {line}")
            level = len(heading[1])
            output.append(f"<h{level}>{inline(heading[2])}</h{level}>")
        elif line.startswith("- "):
            flush()
            if not in_list:
                output.append("<ul>")
                in_list = True
            output.append("<li>" + inline(line[2:]) + "</li>")
        else:
            paragraph.append(line)
    flush()
    if in_list:
        output.append("</ul>")
    return "\n".join(output)


def build():
    sections = []
    for language, filename in [("zh", "CHANGELOG.zh-CN.md"), ("en", "CHANGELOG.md")]:
        content = render_markdown((ROOT / filename).read_text(encoding="utf-8"))
        lang = "zh-CN" if language == "zh" else "en"
        sections.append(f'<section data-language="{language}" lang="{lang}">\n{content}\n</section>')
    return '''<!doctype html>
<!-- Generated by website/build_changelog.py. Edit the root CHANGELOG*.md files. -->
<html lang="zh-CN">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="Git Agent 中英文版本更新日志 / Bilingual version changelog.">
  <title>更新日志 / Changelog — Git Agent</title>
  <link rel="canonical" href="https://git-agent.emssion.com/changelog.html">
  <link rel="icon" type="image/x-icon" sizes="256x256" href="favicon.ico?v=connected-1">
  <link rel="icon" type="image/svg+xml" sizes="any" href="assets/logo-ga.svg?v=connected-1">
  <link rel="stylesheet" href="styles.css?v=real-ui-2">
  <link rel="stylesheet" href="changelog.css?v=1">
  <script src="changelog.js?v=1" defer></script>
</head>
<body>
  <a class="skip-link" href="#main">跳转到更新日志 / Skip to changelog</a>
  <header class="site-header">
    <nav class="container nav-wrap" aria-label="Changelog navigation">
      <a class="brand" href="./" data-home><img src="assets/logo-ga.svg?v=connected-1" alt="" width="40" height="40"><span>Git Agent<span class="brand-dot">.</span></span></a>
      <a class="language-button" href="?lang=en" data-language-toggle>English ↗</a>
    </nav>
  </header>
  <main id="main" class="container changelog">
''' + "\n".join(sections) + '''
    <footer class="download-links">
      <a href="./" data-home>Git Agent ↗</a>
      <a href="https://github.com/adoin/git-Agent/releases">GitHub Releases ↗</a>
      <a href="https://ko-fi.com/adoin">Ko-fi ↗</a>
    </footer>
  </main>
</body>
</html>
'''


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    rendered = build()
    target = PUBLIC / "changelog.html"
    if args.check:
        if not target.is_file() or target.read_text(encoding="utf-8") != rendered:
            raise SystemExit("Stale changelog page: run python website/build_changelog.py")
        print("PASS: website changelog matches both Markdown sources.")
    else:
        target.write_text(rendered, encoding="utf-8", newline="\n")
        print(f"Generated {target}")
